// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test1.domain;

import test1.domain.MyClass;
import test1.domain.mypackage.MyClass2;

privileged aspect MyClass_Roo_JavaBean {
    
    public Byte MyClass.getMyattribute() {
        return this.Myattribute;
    }
    
    public void MyClass.setMyattribute(Byte Myattribute) {
        this.Myattribute = Myattribute;
    }
    
    public MyClass2 MyClass.getMyClass2() {
        return this.myClass2;
    }
    
    public void MyClass.setMyClass2(MyClass2 myClass2) {
        this.myClass2 = myClass2;
    }
    
}
