// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test1.domain;

import org.springframework.beans.factory.annotation.Configurable;
import test1.domain.MyClass;

privileged aspect MyClass_Roo_Configurable {
    
    declare @type: MyClass: @Configurable;
    
}
