// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test1.domain;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;
import test1.domain.MyClass;

privileged aspect MyClass_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager MyClass.entityManager;
    
    public static final EntityManager MyClass.entityManager() {
        EntityManager em = new MyClass().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long MyClass.countMyClasses() {
        return entityManager().createQuery("SELECT COUNT(o) FROM MyClass o", Long.class).getSingleResult();
    }
    
    public static List<MyClass> MyClass.findAllMyClasses() {
        return entityManager().createQuery("SELECT o FROM MyClass o", MyClass.class).getResultList();
    }
    
    public static MyClass MyClass.findMyClass(Long id) {
        if (id == null) return null;
        return entityManager().find(MyClass.class, id);
    }
    
    public static List<MyClass> MyClass.findMyClassEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM MyClass o", MyClass.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void MyClass.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void MyClass.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            MyClass attached = MyClass.findMyClass(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void MyClass.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void MyClass.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public MyClass MyClass.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        MyClass merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
