// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test1.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Version;
import test1.domain.MyClass;

privileged aspect MyClass_Roo_Jpa_Entity {
    
    declare @type: MyClass: @Entity;
    
    @Id
    @SequenceGenerator(name = "myClassGen", sequenceName = "MYCLASS_SEQ")
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "myClassGen")
    @Column(name = "id")
    private Long MyClass.id;
    
    @Version
    @Column(name = "version")
    private Integer MyClass.version;
    
    public Long MyClass.getId() {
        return this.id;
    }
    
    public void MyClass.setId(Long id) {
        this.id = id;
    }
    
    public Integer MyClass.getVersion() {
        return this.version;
    }
    
    public void MyClass.setVersion(Integer version) {
        this.version = version;
    }
    
}
