// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package toto.domain;

import org.springframework.beans.factory.annotation.Configurable;
import toto.domain.LineItem;

privileged aspect LineItem_Roo_Configurable {
    
    declare @type: LineItem: @Configurable;
    
}
