// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package gis.com.restaurant.domain;

import gis.com.restaurant.domain.Plat;

privileged aspect Plat_Roo_JavaBean {
    
    public String Plat.getNbEtoiles() {
        return this.nbEtoiles;
    }
    
    public void Plat.setNbEtoiles(String nbEtoiles) {
        this.nbEtoiles = nbEtoiles;
    }
    
}
