// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package gis.com.restaurant.domain;

import gis.com.restaurant.domain.Serveur;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Serveur_Roo_Configurable {
    
    declare @type: Serveur: @Configurable;
    
}
