// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test1.domain.mypackage;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Version;
import test1.domain.mypackage.MyClass2;

privileged aspect MyClass2_Roo_Jpa_Entity {
    
    declare @type: MyClass2: @Entity;
    
    @Id
    @SequenceGenerator(name = "myClass2Gen", sequenceName = "MYCLASS2_SEQ")
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "myClass2Gen")
    @Column(name = "id")
    private Long MyClass2.id;
    
    @Version
    @Column(name = "version")
    private Integer MyClass2.version;
    
    public Long MyClass2.getId() {
        return this.id;
    }
    
    public void MyClass2.setId(Long id) {
        this.id = id;
    }
    
    public Integer MyClass2.getVersion() {
        return this.version;
    }
    
    public void MyClass2.setVersion(Integer version) {
        this.version = version;
    }
    
}
