// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test1.domain.mypackage;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;
import test1.domain.mypackage.MyClass2;

privileged aspect MyClass2_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager MyClass2.entityManager;
    
    public static final EntityManager MyClass2.entityManager() {
        EntityManager em = new MyClass2().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long MyClass2.countMyClass2s() {
        return entityManager().createQuery("SELECT COUNT(o) FROM MyClass2 o", Long.class).getSingleResult();
    }
    
    public static List<MyClass2> MyClass2.findAllMyClass2s() {
        return entityManager().createQuery("SELECT o FROM MyClass2 o", MyClass2.class).getResultList();
    }
    
    public static MyClass2 MyClass2.findMyClass2(Long id) {
        if (id == null) return null;
        return entityManager().find(MyClass2.class, id);
    }
    
    public static List<MyClass2> MyClass2.findMyClass2Entries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM MyClass2 o", MyClass2.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void MyClass2.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void MyClass2.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            MyClass2 attached = MyClass2.findMyClass2(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void MyClass2.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void MyClass2.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public MyClass2 MyClass2.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        MyClass2 merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
