// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test1.domain.mypackage;

import org.springframework.beans.factory.annotation.Configurable;
import test1.domain.mypackage.MyClass2;

privileged aspect MyClass2_Roo_Configurable {
    
    declare @type: MyClass2: @Configurable;
    
}
