// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test1.domain.mypackage;

import test1.domain.mypackage.MyClass;
import test1.domain.mypackage.MyClass2;

privileged aspect MyClass2_Roo_JavaBean {
    
    public MyClass MyClass2.getAttribute3() {
        return this.attribute3;
    }
    
    public void MyClass2.setAttribute3(MyClass attribute3) {
        this.attribute3 = attribute3;
    }
    
    public long MyClass2.getAttribute2() {
        return this.attribute2;
    }
    
    public void MyClass2.setAttribute2(long attribute2) {
        this.attribute2 = attribute2;
    }
    
    public String MyClass2.getMyattribute() {
        return this.Myattribute;
    }
    
    public void MyClass2.setMyattribute(String Myattribute) {
        this.Myattribute = Myattribute;
    }
    
    public test1.domain.MyClass MyClass2.getMyClass() {
        return this.myClass;
    }
    
    public void MyClass2.setMyClass(test1.domain.MyClass myClass) {
        this.myClass = myClass;
    }
    
}
